name: Ejecutar BID LF cada 2 horas

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  run-bid-lf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
          use-public-rspm: true

      - name: Instalar dependencias del sistema para sf/units
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudunits2-dev libgdal-dev libgeos-dev libproj-dev \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1-dev libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libtiff-dev libjpeg-dev

      # (Opcional pero recomendado) Pre-instalar deps de R según DESCRIPTION/renv si lo tuvieras
      # - name: Instalar dependencias de R declaradas
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages: |
      #       any::pacman
      #       any::dplyr
      #       any::tidyr
      #       any::httr
      #       any::jsonlite
      #       any::googledrive
      #       any::googlesheets4
      #       any::writexl
      #       any::haven
      #       any::stringr
      #       any::labelled
      #       any::lubridate
      #       any::gtsummary
      #       any::dotenv
      #       any::readxl
      #       any::tibble
      #       any::sf
      #       any::purrr

      - name: Instalar paquetes de R (si no usas el paso opcional)
        run: |
          Rscript -e "if (!require('pacman')) install.packages('pacman', repos='https://cloud.r-project.org')"
          Rscript -e "pacman::p_load(dplyr, tidyr, httr, jsonlite, googledrive, googlesheets4, writexl, haven, stringr, labelled, lubridate, gtsummary, dotenv, readxl, tibble, sf, purrr)"

      - name: Ejecutar script maestro BID LF
        env:
          GITHUB_ACTIONS: "true"
          SERVIDOR: ${{ secrets.SERVIDOR }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          FORMID: ${{ secrets.FORMID }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          IDALERTAS: ${{ secrets.IDALERTAS }}
        run: |
          Rscript BID_LF_master_script.R
