name: Ejecutar BID LF cada 2 horas

on:
  schedule:
    - cron: "0 */2 * * *"  # Ejecutar cada 2 horas
  workflow_dispatch:       # Permite ejecución manual desde GitHub Actions

jobs:
  run-bid-lf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Instalar paquetes de R
        run: |
          Rscript -e "if (!require('pacman')) install.packages('pacman', repos='https://cloud.r-project.org')"
          Rscript -e "pacman::p_load(dplyr, tidyr, httr, jsonlite, googledrive, googlesheets4, writexl, haven, stringr, labelled, lubridate, gtsummary, dotenv, readxl, tibble, sf, purrr)"

      - name: Ejecutar script maestro BID LF
        env:
          GITHUB_ACTIONS: "true"
          SERVIDOR: ${{ secrets.SERVIDOR }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          FORMID: ${{ secrets.FORMID }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          IDALERTAS: ${{ secrets.IDALERTAS }}
        run: |
          Rscript BID_LF_master_script.R
